### ISSUE TITLE
JedisUtil类中 JedisPool 没初始化，空指针异常，需要初始化

### ISSUE THREAD

**Issue by impnote** [outman-dd/ssmdemo#1]
` private static JedisPool jedisPool = new JedisPool();`

**Comment by outman-dd** [comment]
jedisPool是通过Spring依赖注入，使用JedisUtil的setJedisPool方法注入的，应该是没有问题的，我这里可以运行成功的

**Comment by impnote** [comment]
仔细看了一下是我断章取义了，我这是用springboot搭的，省去了一堆xml配置，初始化一下可以跑起来。你用的spring，之前没看你的xml,应该是没问题的。
